/*TD1*/
CREATE TABLE THEME (
	id int(5) PRIMARY KEY AUTO_INCREMENT,
	nom VARCHAR(50) NOT NULL UNIQUE,
	logo BLOB
);

CREATE TABLE DOMAINE (
	id int(5) PRIMARY KEY AUTO_INCREMENT,
	nom VARCHAR(50) NOT NULL UNIQUE,
	logo BLOB,
	theme int(5),
    FOREIGN KEY (theme) REFERENCES THEME(id) ON DELETE CASCADE
);

CREATE TABLE COMPETENCES (
	id int(5) PRIMARY KEY AUTO_INCREMENT,
	compétence VARCHAR(50) NOT NULL UNIQUE,
   etat int(1) DEFAULT 0,
	domaine int(5),
    FOREIGN KEY (domaine) REFERENCES DOMAINE(id) ON DELETE CASCADE
);

/*TD2*/
CREATE TABLE UTILISATEURS (
   login VARCHAR(20) NOT NULL UNIQUE,
	password CHAR(128) NOT NULL,
	email VARCHAR(320) UNIQUE, 
	date_inscription DATE,
	derniere_connexion DATE
);

